sudo: false
language: python
python:
#  - 2.6
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
install:
    - pip install -r requirements/test.txt
script:
    - pyver=$(python --version 2>&1 | awk '{print substr($2, 0, 3)}');
      case $pyver in
        2.7) tox -e "py${pyver//\.}-{std,coverage}";;
        *) tox -e "py${pyver//\.}-std";;
      esac
after_success:
    - coveralls
